### ISSUE TITLE
Unnecessary Notification sounds

### ISSUE THREAD

**Issue by jsrockstaranks** [enteraname74/SoulSearching#8] opened 2023-10-28 19:08 UTC
Notification sound fires for every new song when is starts playing and that sound plays when we change the current playing pointer on the tracing bar.

**Comment by enteraname74** [comment] 2023-10-28 20:33
I saw this problem earlier today, it can happen in multiple occasions. It will be fixed in the next release.

**Comment by enteraname74** [comment] 2023-10-30 18:58
Normally, the problem is solved in the new release (v0.2.2) of the application. Let me know if it's all good for you.

**Comment by enteraname74** [comment] 2023-11-21 10:41
Because of no returns from the concerned user, I will close this issue.

**Closed by enteraname74** 2023-11-21 10:41 UTC
